### ISSUE TITLE
Catalan Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/ca.reactjs.org#1]
## Maintainer List

* @pepjo
* @seraco
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@ragafus) #11
* [x] Tutorial (@pepjo) #12

### Basics

* [x] Hello World (@pepjo) #13
* [x] Introducing JSX (@seraco) #16 
* [x] Rendering Elements (@pepjo) #14 
* [x] Components and Props (@pepjo) #15
* [x] State and Lifecycle (@pepjo) #18 
* [x] Handling Events (@seraco) #20
* [x] Conditional Rendering (@seraco) #22
* [x] Lists and Keys (@nglvnyls) #77
* [x] Forms (@pepjo) #21
* [x] Lifting State Up (@seraco) #30
* [x] Composition vs Inheritance (@seraco) #31
* [x] Thinking in React (@seraco) #32

### API Reference

* [ ] React (@nglvnyls)
* [ ] React.Component (@jvidalv)
* [x] ReactDOM (@nglvnyls) #80
* [x] ReactDOMServer (@nglvnyls) #82
* [x] DOM Elements (@nglvnyls) #83
* [x] SyntheticEvent (@nglvnyls) #86
* [x] Test Utilities (@nglvnyls) #87
* [ ] Shallow Renderer
* [x] Test Renderer (@nglvnyls) #88
* [x] JS Environment Requirements (@nglvnyls) #90
* [x] Glossary (@nglvnyls) #91

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml (@pepjo) #12
* [ ] docs/nav.yml (@seraco)

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [ ] Getting Started
* [ ] Add React to a Website
* [ ] Create a New React App
* [ ] CDN Links

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [ ] Introducing Hooks
  * [ ] Hooks at a Glance
  * [ ] Using the State Hook
  * [ ] Using the Effect Hook
  * [ ] Rules of Hooks
  * [ ] Building Your Own Hooks
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [x] Accessibility (@nglvnyls) #76
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [x] Forwarding Refs (@nglvnyls) #79
* [ ] Fragments
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by casvil** [comment]
I guess README should be translated as well, PR created https://github.com/reactjs/ca.reactjs.org/pull/2

**Comment by seraco** [comment]
@tesseralis Should README also be added in the Translation Progress file, in order that it is also taken into account for the progress of the translation?

**Comment by tesseralis** [comment]
@seraco @casvil It's not part of the website itself, so it doesn't go here, but other languages have translated the README too!

**Comment by ragafus** [comment]
I would like to translate **Home Page**

**Comment by seraco** [comment]
Sure @ragafus, feel free to translate it.

**Comment by tesseralis** [comment]
Hey @pepjo @seraco @ragafus  how is the translation going?

**Comment by ragafus** [comment]
I will finish **Home Page** translation by the end of the week.

**Comment by ragafus** [comment]
@seraco @pepjo I would like to translate **Tutorial**.

**Comment by pepjo** [comment]
@ragafus , sorry I just saw this. I finished the translation of Tutorial, feel free to review it.

**Comment by pepjo** [comment]
@tesseralis we are going to finish! I've been very busy this last month, but I'd like to push to see react translated to catalan :)

**Comment by pepjo** [comment]
I am going to translate Basics -> Hello World

**Comment by seraco** [comment]
I'll translate **Introducing JSX**

**Comment by seraco** [comment]
I'll also translate **Handling Events** and **Contidional Rendering**

**Comment by ragafus** [comment]
I'll translate **Lists and Keys**.

**Comment by seraco** [comment]
@ragafus Next time, also try to edit the description of this issue and write you usename next to the section you are going to translate. It's faster to spot than having to read through the comments.

**Comment by seraco** [comment]
I'll also do *docs/nav.yml*

**Comment by pepjo** [comment]
I am going to translate Froms

**Comment by seraco** [comment]
I'm going to translate **Lifting State Up** and **Composition vs Inheritance**

**Comment by seraco** [comment]
@ragafus, do you plan to translate **Lists and Keys** soon? If not I will take that section so that we can finish the **Basics**.

**Comment by seraco** [comment]
I'm also translating **Thinking In React** and **React** sections.

**Comment by jvidalv** [comment]
Hi, I'll start with **API Reference** => **React.Component**

**Comment by nglvnyls** [comment]
hi everybody. 
I forked the project in order to help to translate.
I was able to run English version locally , but not catalan, so I think it's because that is outdated.
Can anyone update the catalan repository in order to contribute to translate? Ty

**Comment by pepjo** [comment]
Hi @nglvnyls, I'll do it now. I'll update you when it's done.

**Comment by nglvnyls** [comment]
hi @pepjo, @seraco . 

I push ready for review PR#79 Traduccio_docs/Fowarding_Ref , and pr#76 docs-accessibility

I can't solve problems in pr#75 list-and-keys translation, so I closed #75 and I made a copy ( #77), and fix all review's comments

**Comment by pepjo** [comment]
Hi @nglvnyls,

Thanks for your work, I will review it later today ☺️

Best,
Pep

**Comment by nglvnyls** [comment]
Hi @pepjo, @seraco . Començo la traducció d'API REFERENCE/ ReactDOMServer

**Comment by nglvnyls** [comment]
PR#82-->  [Traduccio API-ReactDOMServer #82](https://github.com/reactjs/ca.reactjs.org/pull/82)  --> ready for review

**Comment by nglvnyls** [comment]
Hi @pepjo, @seraco . Començo la traducció d'API REFERENCE/ DOM Elements

**Comment by nglvnyls** [comment]
Hi @pepjo, @seraco .

PR#80--> [Traduccio REFERENCIA API- ReactDom #80](https://github.com/reactjs/ca.reactjs.org/pull/80) --> review's issues fixed. (Ex 71)
PR#82--> [Traduccio API-ReactDOMServer #82](https://github.com/reactjs/ca.reactjs.org/pull/82) --> ready for review
PR#83--> [Traduccio API- DOM Elements #83](https://github.com/reactjs/ca.reactjs.org/pull/83) --> ready for review

**Comment by nglvnyls** [comment]
Hi @pepjo, @seraco . Començo la traducció d'API REFERENCE/ Events

**Comment by nglvnyls** [comment]
Hi @pepjo, @seraco . Començo la traducció d'API REFERENCE/ Events ---> ready for review

**Comment by nglvnyls** [comment]
Hi @pepjo, @seraco . Començo la traducció d'API REFERENCE/ Test Utilities

**Comment by nglvnyls** [comment]
Hi @pepjo, @seraco . Començo la traducció d'[API REFERENCE/ Test Renderer](https://reactjs.org/docs/test-renderer.html)

**Comment by nglvnyls** [comment]
Hi @pepjo, @seraco . Començo la traducció d'API REFERENCE/ JS Environment Requirements

**Comment by nglvnyls** [comment]
Hi @pepjo, @seraco . Començo la traducció d'[API REFERENCE/ Glossary](https://reactjs.org/docs/glossary.html)

**Comment by nglvnyls** [comment]
Hi @jvidalv. Tens assignada la traducció de  d'API REFERENCE/  React.Component . No sé si la tens molt avançada, però si no es així, la puc completar jo.

**Comment by nglvnyls** [comment]
Hi @seraco. Tens assignada la traducció de  d'API REFERENCE/ React . No sé si la tens molt avançada, però si no es així, la puc completar jo.

**Comment by seraco** [comment]
> Hi @seraco. Tens assignada la traducció de d'API REFERENCE/ React . No sé si la tens molt avançada, però si no es així, la puc completar jo.

@nglvnyls, feel free to complete it. 🙂

**Comment by jvidalv** [comment]
Hi @nglvnyls, as @seraco said, feel free to complete it, I didn't had the spirit to translate it hahah

In any case maybe its worth to look at this before continue:
https://github.com/reactjs/reactjs.org/issues/3308

**Comment by nglvnyls** [comment]
thanks for advice @jvidalv. 
Yes, it may be that when we finish the translation it will be outdated, but I think it cans help with the translation of v.2, fixing React terms translations. At least I would like to finish api reference 🙂

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
